version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
    networks:
      - jenkins_network

networks:
  jenkins_network:

volumes:
  jenkins_home:

